### ISSUE TITLE
Image Shrinker offered despite wrong files selected.

### ISSUE THREAD

**Issue by chrisspiegl** [Acidham/alfred-image-shrinker#2]
Image shrinker is offered as a file action as soon as at least one file is an image file (and for example also having selected a text file / svg file / etc).

This introduces an error so that the files do get copied, but somewhere there is an error and the process does not complete properly (files are not resized).

Maybe this can be improved with some kind of input check / filter.

**Comment by chrisspiegl** [comment]
I tested and it seems to work in some cases (with a `jpg` + `css` file for example).

Though, I did not get it to work with a `png` and `svg` file selected. In this case, it just copied the `png` file, did not copy the `svg`, but the `png` also did not get resized.

Tested the same with a `jpg` and `svg` file and the issue was the same.

**Comment by Acidham** [comment]
Automator Tasks are not supporting svg images. On the other hand those can be trespassed when selecting multiple files similar to css or txt. 
I am checking for mime type `image` and svg also returns `image`.

**Comment by Acidham** [comment]
I created version 1.4.1 and removed mimetype detection to a list of accepted files (ext). It should work now even when SVG is part of the selected files

**Comment by chrisspiegl** [comment]
This I think looks more predictable for the short term.

If the mimetype detection would be "deeper" and also get the suffix (aka `image/…`) it may not be a problem but if it just spits out `mimetype = image` it's a bit broad since it may also try to shrink RAW image files which should not be possible.

Solid work 👍.

**Comment by chrisspiegl** [comment]
Troubleshooting I found that jpg files were being ignored because of a missing comma. Fixed it the above commit [7508f27](https://github.com/chrisspiegl/alfred-image-shrinker/commit/7508f279366ea34b141a4b9b71effab61db715ac) and also appended the one after `heic` to prevent accidents.

**Comment by Acidham** [comment]
thx
